[package]
name = "deflate"
version = "0.1.0"
edition = "2021"

[dependencies]
adler = "1.0.2"
clap = { version = "4.5.23", features = ["derive"] }
crc32fast = "1.4.2"
fxhash = "0.2.1"
indicatif = "0.17.9"
nom = "7.1.3"

[profile.release]
debug = 2 
